export const allergensList = [
  "gluten",
  "crustáceos",
  "huevos",
  "pescado",
  "cacahuetes",
  "soja",
  "lácteos",
  "frutos de cáscara",
  "apio",
  "mostaza",
  "granos de sésamo",
  "dióxido de azufre y sulfitos",
  "altramuces",
  "moluscos",
];
