name: Python application

on:
  pull_request:
    branches:
      - main
      - develop

jobs:

  PrTitleChecker:
    if: |
      github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: ".github/pr-title-checker-config.json"

